[variables]
NODE_VERSION = "20"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

[staticAssets]
"public" = "./"
".next/static" = "./_next/static"
